name: buildings
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - r-base=4.1.3
  - rpy2=3.5.11
  - pip
  - git
  - numpy
  - pandas=2.0.3
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - openpyxl
  - pyyaml
  - requests
  - pyreadr
  - xlrd
  - typing-extensions
  - tzlocal
  - setuptools
  - jinja2
  - six
  - pyparsing
  - python-dateutil
  - python-tzdata
  - xlsxwriter

  - pip:
      - boto3
      - botocore
      - s3transfer
      - python-dotenv
      - git+https://github.com/leoal2/flowsa_CARB_version.git
