name: buildings
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1
  - _r-mutex=1.0.1
  - aom=3.9.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.0
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.1
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - blosc=1.21.6
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2025.2.25
  - cairo=1.18.0
  - capnproto=1.0.2
  - cffi=1.17.1
  - cfitsio=4.4.1
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - dav1d=1.2.1
  - et_xmlfile=1.1.0
  - fiona=1.10.1
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.10.0
  - geos=3.13.0
  - geotiff=1.7.3
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - intel-openmp=2024.2.1
  - jinja2=3.1.5
  - kealib=1.5.3
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflang=19.1.4
  - libgdal=3.10.0
  - libgdal-core=3.10.0
  - libgdal-fits=3.10.0
  - libgdal-grib=3.10.0
  - libgdal-hdf4=3.10.0
  - libgdal-hdf5=3.10.0
  - libgdal-jp2openjpeg=3.10.0
  - libgdal-kea=3.10.0
  - libgdal-netcdf=3.10.0
  - libgdal-pdf=3.10.0
  - libgdal-pg=3.10.0
  - libgdal-postgisraster=3.10.0
  - libgdal-tiledb=3.10.0
  - libgdal-xls=3.10.0
  - libglib=2.82.2
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libheif=1.18.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-pcre2=10.34
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - markupsafe=3.0.2
  - minizip=4.0.6
  - mkl=2024.2.2
  - msys2-conda-epoch=20160418
  - numexpr=2.10.2
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.1
  - packaging=24.2
  - pcre2=10.44
  - pip=24.2
  - pixman=0.43.4
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=17.2
  - proj=9.5.0
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pyparsing=3.2.0
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytz=2025.1
  - r-base=4.1.3
  - rav1e=0.6.6
  - re2=2024.07.02
  - rpy2=3.5.11
  - setuptools=73.0.1
  - shapely=2.0.6
  - simplegeneric=0.8.1
  - six=1.16.0
  - snappy=1.2.1
  - spdlog=1.14.1
  - sqlite=3.47.0
  - svt-av1=2.3.0
  - tbb=2021.13.0
  - tiledb=2.26.2
  - tk=8.6.13
  - tzdata=2024a
  - tzlocal=5.3
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - x265=3.5
  - xerces-c=3.2.5
  - xlsxwriter=3.2.0
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - altgraph==0.17.4
      - appdirs==1.4.4
      - asn1crypto==1.5.1
      - bibtexparser==1.4.3
      - boto3==1.35.90
      - botocore==1.35.90
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - contourpy==1.3.0
      - cryptography==43.0.1
      - cycler==0.12.1
      - distro==1.9.0
      - filelock==3.16.0
      - flowsa==2.0.4
      - fonttools==4.54.1
      - fuzzywuzzy==0.18.0
      - idna==3.8
      - jmespath==1.0.1
      - joblib==1.4.2
      - kaleido==0.1.0.post1
      - kiwisolver==1.4.7
      - levenshtein==0.26.1
      - matplotlib==3.9.2
      - narwhals==1.26.0
      - numpy==1.26.4
      - olca-schema==2.4.0
      - pandas==2.0.3
      - patsy==1.0.1
      - pefile==2023.2.7
      - pillow==11.0.0
      - platformdirs==4.3.2
      - plotly==6.0.0
      - pyarrow==18.1.0
      - pycountry==24.6.1
      - pyinstaller==6.11.1
      - pyinstaller-hooks-contrib==2024.10
      - pyjwt==2.9.0
      - pyopenssl==24.2.1
      - pyreadr==0.5.2
      - python-dotenv==1.0.1
      - python-levenshtein==0.26.1
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.2
      - rapidfuzz==3.12.1
      - requests==2.32.3
      - requests-ftp==0.3.1
      - s3transfer==0.10.2
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - snowflake-connector-python==3.12.1
      - sortedcontainers==2.4.0
      - statsmodels==0.14.4
      - tabula-py==2.10.0
      - threadpoolctl==3.5.0
      - tomlkit==0.13.2
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - xlrd==2.0.1
